name = "family-travel-tracker"
compatibility_date = "2025-01-01"

# Cloudflare Pages will read this for D1 bindings in production.
[[d1_databases]]
binding = "DB"
database_name = "family-travel-tracker"
database_id = "9aead501-334c-4256-9626-71de9b543ab6"
